# Generated by Django 3.2.19 on 2023-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Course_joied',
            new_name='Course_joined',
        ),
    ]
